//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarberShopManager.Domain.Reports.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceReportMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceReportMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BarberShopManager.Domain.Reports.Resources.ResourceReportMessages", typeof(ResourceReportMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client.
        /// </summary>
        public static string CLIENT {
            get {
                return ResourceManager.GetString("CLIENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string DATE {
            get {
                return ResourceManager.GetString("DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to John&apos;s BarberShop.
        /// </summary>
        public static string JOHNS_BARBERSHOP {
            get {
                return ResourceManager.GetString("JOHNS_BARBERSHOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observation.
        /// </summary>
        public static string OBSERVATION {
            get {
                return ResourceManager.GetString("OBSERVATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        public static string SERVICE {
            get {
                return ResourceManager.GetString("SERVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beard.
        /// </summary>
        public static string SERVICE_TYPE_BEARD {
            get {
                return ResourceManager.GetString("SERVICE_TYPE_BEARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female Haircut.
        /// </summary>
        public static string SERVICE_TYPE_FEMALE_HAIRCUT {
            get {
                return ResourceManager.GetString("SERVICE_TYPE_FEMALE_HAIRCUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haircut and Beard.
        /// </summary>
        public static string SERVICE_TYPE_HAIRCUT_AND_BEAR {
            get {
                return ResourceManager.GetString("SERVICE_TYPE_HAIRCUT_AND_BEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male Haircut.
        /// </summary>
        public static string SERVICE_TYPE_MALE_HAIRCUT {
            get {
                return ResourceManager.GetString("SERVICE_TYPE_MALE_HAIRCUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services from.
        /// </summary>
        public static string SERVICES_FROM {
            get {
                return ResourceManager.GetString("SERVICES_FROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string VALUE {
            get {
                return ResourceManager.GetString("VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly Revenue.
        /// </summary>
        public static string WEEKLY_REVENUE {
            get {
                return ResourceManager.GetString("WEEKLY_REVENUE", resourceCulture);
            }
        }
    }
}
